name: workflow1
on:
  push:
jobs:
  job1:
    runs-on: self-hosted
    steps:
    - name: step1
      uses: actions/checkout@v4
    - name: step2
      run: ls -larth
    - name: step3
      run: |
        docker --version
        docker build -t myfirst:v1.0 .
        docker images
        docker run --name myfirst myfirst:v1.0
        echo "the image got created and the container is running"